### ISSUE TITLE
关于textnow被封号问题

### ISSUE THREAD

**Issue by yiJayzhiming** [aaronlam/textnow-autosend#2]

**Comment by yiJayzhiming** [comment]
2个号已被封禁，估计是自动回复过于频繁，大家用时改下自动回复频率吧

**Comment by aaronlam** [comment]
> 2个号已被封禁，估计是自动回复过于频繁，大家用时改下自动回复频率吧

我也注意到这个问题，你可以直接用找回密码查看自己真实的账号名是什么，然后把TEXTNOW_USERNAME参数值换成该真实账号名，就可以解决该问题。另外也建议把频率降低。

**Comment by aaronlam** [comment]
找回密码的邮件中会有真实账户名，如图：

![TextNow找回密码邮件](https://cdn.jsdelivr.net/gh/aaronlam/imghosting/20201119013920.png)

**Comment by yiJayzhiming** [comment]
> > 2个号已被封禁，估计是自动回复过于频繁，大家用时改下自动回复频率吧
> 
> 我也注意到这个问题，你可以直接用找回密码查看自己真实的账号名是什么，然后把TEXTNOW_USERNAME参数值换成该真实账号名，就可以解决该问题。另外也建议把频率降低。

> > 2个号已被封禁，估计是自动回复过于频繁，大家用时改下自动回复频率吧
> 
> 我也注意到这个问题，你可以直接用找回密码查看自己真实的账号名是什么，然后把TEXTNOW_USERNAME参数值换成该真实账号名，就可以解决该问题。另外也建议把频率降低。



> > 2个号已被封禁，估计是自动回复过于频繁，大家用时改下自动回复频率吧
> 
> 我也注意到这个问题，你可以直接用找回密码查看自己真实的账号名是什么，然后把TEXTNOW_USERNAME参数值换成该真实账号名，就可以解决该问题。另外也建议把频率降低。



> > 2个号已被封禁，估计是自动回复过于频繁，大家用时改下自动回复频率吧
> 
> 我也注意到这个问题，你可以直接用找回密码查看自己真实的账号名是什么，然后把TEXTNOW_USERNAME参数值换成该真实账号名，就可以解决该问题。另外也建议把频率降低。

好的，多谢作者的解决方案
