### ISSUE TITLE
加入多帐号支持

### ISSUE THREAD

**Issue by xigua0123** [aaronlam/textnow-autosend#5]
大佬可以加入多帐号支持吗，？/n或者&分割

**Comment by aaronlam** [comment]
有考虑过这个功能，后续会着手增加这个功能，不过最近可能都暂时没时间去弄。如果愿意的话，可以帮忙改进提个PR。

**Comment by xigua0123** [comment]
https://github.com/Arronlong/py_scripts找到这个库，看说明不支持中文，大佬参考下，弄成支持中文的，

**Comment by aaronlam** [comment]
已经支持多帐号模式，配置用户名和密码时使用 | 符号来进行分隔。
另外需要删掉原来 Fork 的仓库，重新 Fork 之后再进行配置才生效。

**Comment by GV13057911485** [comment]
it is great for multi-accounts, great job.
how many account maximum allowed?
