### ISSUE TITLE
自 2021.1.21 开始程序无法在 Github Action 上工作

### ISSUE THREAD

**Issue by jimlee2048** [aaronlam/textnow-autosend#7]
Github Action 报错，以下是输出信息：
```
Run node index.js
textnow bot start...
Importing existing cookies...
Failed to import existing cookies.
Logging in with existing cookies
Failed to log in with existing cookies.
Logging in with account credentials...
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/runner/work/textnow-autosend/textnow-autosend/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/home/runner/work/textnow-autosend/textnow-autosend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at async Frame.waitForNavigation (/home/runner/work/textnow-autosend/textnow-autosend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:441:16)
    at async Page.waitForNavigation (/home/runner/work/textnow-autosend/textnow-autosend/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:813:16)
    at async Promise.all (index 1)
    at async Object.module.exports.logIn (/home/runner/work/textnow-autosend/textnow-autosend/utils/helper.js:20:5)
    at async /home/runner/work/textnow-autosend/textnow-autosend/index.js:45:17
Error: Process completed with exit code 1.
```
我看您这边的 Github Action 昨天开始也出现了同样的问题

**Comment by slamdunkdlink** [comment]
遇到同样的问题,Action也报错了,等作者解决吧

**Comment by GV13057911485** [comment]
我也遇到同样的问题，请作者大神出手解决。

**Comment by aaronlam** [comment]
感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过 
hCaptcha 验证机制的，可以一起探讨一下。。

**Comment by GV13057911485** [comment]
感谢aaronlam同学回复。
TEXTNOW在熟悉的电脑上登陆，不会出现Hcaptcha，这个思路希望对你有帮助。

**Comment by uxgood** [comment]
> 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> hCaptcha 验证机制的，可以一起探讨一下。。

或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。

**Comment by aaronlam** [comment]
> > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > hCaptcha 验证机制的，可以一起探讨一下。。
> 
> 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。

其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。

**Comment by jimlee2048** [comment]
> > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > hCaptcha 验证机制的，可以一起探讨一下。。
> > 
> > 
> > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> 
> 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。

或许可以试试通过引入新的secret手动向脚本输入cookies？
我这边尝试自己修改了下：
github上添加相应secret，`action.yml` 和 `config\index.js` 下引入相应变量，向主脚本 `index.js`添加代码
```
    // Importing cookies from secret
    try {
      console.log("Importing cookies from secret...");
      cookies = cookiesInput;
    } catch (error) {
      console.log("Failed to import cookies from secret.");
    }
```
`cookiesInput`继承新添加的 cookies 的 secret
在我的电脑上通过在`config\index.js`下指定`cookiesInput`运行正常，
但在 github action 上部署异常，脚本无法使用 github 上的 secret 指定的 cookies 进行登陆。
奇怪的是，在`index.js`上直接指定cookies值后, github action 上反而运行正常，能够正常的登陆发信。
我不太懂 js，上面说的可能不太清楚，现在也没有思路了，希望我的瞎折腾对您有帮助。
考虑到还是没能解决问题，我改的东西就先不提交 pull request 了，需要的话我随时可以交一份

**Comment by uxgood** [comment]
> > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > hCaptcha 验证机制的，可以一起探讨一下。。
> > 
> > 
> > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> 
> 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。

 GitHub 的 Action 中是可以保存cache的呀。可以用actions/cache@v2

**Comment by xiaokaixuan** [comment]
> > > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > > hCaptcha 验证机制的，可以一起探讨一下。。
> > > 
> > > 
> > > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> > 
> > 
> > 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。
> 
> 或许可以试试通过引入新的secret手动向脚本输入cookies？
> 我这边尝试自己修改了下：
> github上添加相应secret，`action.yml` 和 `config\index.js` 下引入相应变量，向主脚本 `index.js`添加代码
> 
> ```
>     // Importing cookies from secret
>     try {
>       console.log("Importing cookies from secret...");
>       cookies = cookiesInput;
>     } catch (error) {
>       console.log("Failed to import cookies from secret.");
>     }
> ```
> 
> `cookiesInput`继承新添加的 cookies 的 secret
> 在我的电脑上通过在`config\index.js`下指定`cookiesInput`运行正常，
> 但在 github action 上部署异常，脚本无法使用 github 上的 secret 指定的 cookies 进行登陆。
> 奇怪的是，在`index.js`上直接指定cookies值后, github action 上反而运行正常，能够正常的登陆发信。
> 我不太懂 js，上面说的可能不太清楚，现在也没有思路了，希望我的瞎折腾对您有帮助。
> 考虑到还是没能解决问题，我改的东西就先不提交 pull request 了，需要的话我随时可以交一份

目前没啥完美方案了，只能先用Cookie登录。我加了个Cookie的Secret配置。[kaixuan1115/textnow-autosend](https://github.com/kaixuan1115/textnow-autosend)

**Comment by jimlee2048** [comment]
> > > > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > > > hCaptcha 验证机制的，可以一起探讨一下。。
> > > > 
> > > > 
> > > > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> > > 
> > > 
> > > 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。
> > 
> > 
> > 或许可以试试通过引入新的secret手动向脚本输入cookies？
> > 我这边尝试自己修改了下：
> > github上添加相应secret，`action.yml` 和 `config\index.js` 下引入相应变量，向主脚本 `index.js`添加代码
> > ```
> >     // Importing cookies from secret
> >     try {
> >       console.log("Importing cookies from secret...");
> >       cookies = cookiesInput;
> >     } catch (error) {
> >       console.log("Failed to import cookies from secret.");
> >     }
> > ```
> > 
> > 
> > `cookiesInput`继承新添加的 cookies 的 secret
> > 在我的电脑上通过在`config\index.js`下指定`cookiesInput`运行正常，
> > 但在 github action 上部署异常，脚本无法使用 github 上的 secret 指定的 cookies 进行登陆。
> > 奇怪的是，在`index.js`上直接指定cookies值后, github action 上反而运行正常，能够正常的登陆发信。
> > 我不太懂 js，上面说的可能不太清楚，现在也没有思路了，希望我的瞎折腾对您有帮助。
> > 考虑到还是没能解决问题，我改的东西就先不提交 pull request 了，需要的话我随时可以交一份
> 
> 目前没啥完美方案了，只能先用Cookie登录。我加了个Cookie的Secret配置。[kaixuan1115/textnow-autosend](https://github.com/kaixuan1115/textnow-autosend)

脚本可用，学习了，非常感谢！

**Comment by mingjing99** [comment]
> > > > > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > > > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > > > > hCaptcha 验证机制的，可以一起探讨一下。。
> > > > > 
> > > > > 
> > > > > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> > > > 
> > > > 
> > > > 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。
> > > 
> > > 
> > > 或许可以试试通过引入新的secret手动向脚本输入cookies？
> > > 我这边尝试自己修改了下：
> > > github上添加相应secret，`action.yml` 和 `config\index.js` 下引入相应变量，向主脚本 `index.js`添加代码
> > > ```
> > >     // Importing cookies from secret
> > >     try {
> > >       console.log("Importing cookies from secret...");
> > >       cookies = cookiesInput;
> > >     } catch (error) {
> > >       console.log("Failed to import cookies from secret.");
> > >     }
> > > ```
> > > 
> > > 
> > > `cookiesInput`继承新添加的 cookies 的 secret
> > > 在我的电脑上通过在`config\index.js`下指定`cookiesInput`运行正常，
> > > 但在 github action 上部署异常，脚本无法使用 github 上的 secret 指定的 cookies 进行登陆。
> > > 奇怪的是，在`index.js`上直接指定cookies值后, github action 上反而运行正常，能够正常的登陆发信。
> > > 我不太懂 js，上面说的可能不太清楚，现在也没有思路了，希望我的瞎折腾对您有帮助。
> > > 考虑到还是没能解决问题，我改的东西就先不提交 pull request 了，需要的话我随时可以交一份
> > 
> > 
> > 目前没啥完美方案了，只能先用Cookie登录。我加了个Cookie的Secret配置。[kaixuan1115/textnow-autosend](https://github.com/kaixuan1115/textnow-autosend)
> 
> 脚本可用，学习了，非常感谢！

我也试了试这个脚本，但还是同样的错误，总是不成功
觉得是我取得的cookie不对，请问用下面的办法可以么？
1.单击鼠标右键，选择检查或审查元素。
2.点击Console,输入指令 document.cookie,回车即可显示出当前页面cookie信息。
能分享一下如何取得cookie并输入到脚本么？谢谢先！

**Comment by jimlee2048** [comment]
> > > > > > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > > > > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > > > > > hCaptcha 验证机制的，可以一起探讨一下。。
> > > > > > 
> > > > > > 
> > > > > > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> > > > > 
> > > > > 
> > > > > 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。
> > > > 
> > > > 
> > > > 或许可以试试通过引入新的secret手动向脚本输入cookies？
> > > > 我这边尝试自己修改了下：
> > > > github上添加相应secret，`action.yml` 和 `config\index.js` 下引入相应变量，向主脚本 `index.js`添加代码
> > > > ```
> > > >     // Importing cookies from secret
> > > >     try {
> > > >       console.log("Importing cookies from secret...");
> > > >       cookies = cookiesInput;
> > > >     } catch (error) {
> > > >       console.log("Failed to import cookies from secret.");
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > > `cookiesInput`继承新添加的 cookies 的 secret
> > > > 在我的电脑上通过在`config\index.js`下指定`cookiesInput`运行正常，
> > > > 但在 github action 上部署异常，脚本无法使用 github 上的 secret 指定的 cookies 进行登陆。
> > > > 奇怪的是，在`index.js`上直接指定cookies值后, github action 上反而运行正常，能够正常的登陆发信。
> > > > 我不太懂 js，上面说的可能不太清楚，现在也没有思路了，希望我的瞎折腾对您有帮助。
> > > > 考虑到还是没能解决问题，我改的东西就先不提交 pull request 了，需要的话我随时可以交一份
> > > 
> > > 
> > > 目前没啥完美方案了，只能先用Cookie登录。我加了个Cookie的Secret配置。[kaixuan1115/textnow-autosend](https://github.com/kaixuan1115/textnow-autosend)
> > 
> > 
> > 脚本可用，学习了，非常感谢！
> 
> 我也试了试这个脚本，但还是同样的错误，总是不成功
> 觉得是我取得的cookie不对，请问用下面的办法可以么？
> 1.单击鼠标右键，选择检查或审查元素。
> 2.点击Console,输入指令 document.cookie,回车即可显示出当前页面cookie信息。
> 能分享一下如何取得cookie并输入到脚本么？谢谢先！

参见[这里](https://github.com/kaixuan1115/textnow-autosend/commit/f7da699ba90d694f1744bf0756f42dcaa37cb7d9#commitcomment-46294045)

**Comment by mingjing99** [comment]
> 参见[这里](https://github.com/kaixuan1115/textnow-autosend/commit/f7da699ba90d694f1744bf0756f42dcaa37cb7d9#commitcomment-46294045)

感谢！感谢！脚本运行成功！

**Comment by GV13057911485** [comment]
github action是可以开缓存的，我不懂JS，各位有能力的试一下，主动刷新cookies文件至缓存，这样就可以永不过期了，期待王者归来 : -)

uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ runner.os }}-build-${{ runner.os }}-

**Comment by xiaokaixuan** [comment]
> > > > 感谢！已经发现了这个问题，目前还在分析怎么突破。无法正常运行的原因是 TextNow 在登录入口增加了图片识别的验证码机制（
> > > > hCaptcha），所以导致自动运行程序在进行自动登录时，没办法正常进入到短信发送界面，如果有同学有绕过
> > > > hCaptcha 验证机制的，可以一起探讨一下。。
> > > 
> > > 
> > > 或许可以用打码平台。。另外保存cookie而不是每次登录是个好主意。
> > 
> > 
> > 其实目前是支持 Cookie 登录的，不过由于我们现在是跑在 GitHub 的 Action 中，登陆后的 Cookie 并没有被保存下来，也没有办法保存下来（Action 的环境是临时的），如果是跑在服务端的话是可以被保存下来的。
> 
> GitHub 的 Action 中是可以保存cache的呀。可以用actions/cache@v2

改了下，用上了actions/cache@v2，每次登录后会保存新的Cookie，理论上应该不会过期了。[kaixuan1115/textnow-autosend](https://github.com/kaixuan1115/textnow-autosend)

**Comment by xiaokaixuan** [comment]
经过4个月的持续验证，使用`actions/cache@v2`的方案是稳定可行的，期间并未出现Cookie过期的现象。

**Comment by GV13057911485** [comment]
> 经过4个月的持续验证，使用`actions/cache@v2`的方案是稳定可行的，期间并未出现Cookie过期的现象。

确实是非常稳定可靠，我的程序运行中出现过几天中断，原因是billing 问题，github要向我收费了，我没有理会，过几天自己又好了。

**Comment by Oscaner** [comment]
把 hCaptcha 的问题给修了，但是需要 3 美刀。
因为 2captcha.com 的 API 请求要求你的账户里必须有钱，3美刀是能够充值的最小额度，
每一次 API 请求大概需要 0.00299 美刀，不过我把 cookie cache 给支持上了。
之后应该就只有第一次部署会调一次 API，之后能直接拿 cookie cache 登陆，就不需要调 API 了。

---
顺便，puppeteer 的 waitFor() 要弃用了，换成了 waitForTimeout(), 嘿嘿。

**Comment by aaronlam** [comment]
感谢 @ye4241 贡献的代码，目前已解决 Github Action 无法正常工作的问题。最新的代码采用以 cookie 的方式进行用户的登录操作，一定程度上可以防止 TextNow 在程序登录的过程弹出 hCaptcha 的验证框。大家可以 fork 最新版本使用，再次感谢！

**Comment by Oscaner** [comment]
Thief.
